# Site settings
title: Pragmatic Sailor
email: pragmaticsailor@gmail.com
description: Pragmatic stuff about sailing
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
enable_retina: false
permalink: :title
nav_list:
  Home : ['Home', '/', 'fa-home']
  About : ['About', '/about', 'fa-anchor']
single_footer: '<p>Dream in a pragmatic way. -Aldous Huxley</p>'
footer_links:
    About: ['About', '/about']


# Build settings
# markdown: kramdown
